In [1]:
import numpy as np

In [6]:
# input_D = 2
# n = 3
# output_D = 4
X = np.array([[1,2],
              [3,4],
              [5,6]])
W = np.array([[1,7,6,8],
              [0,8,2,4]])
b = np.array([[1,2,3,5]])

In [7]:
print("X: ", X.shape)
print("W: ", W.shape)
print("b: ", b.shape)


X:  (3, 2)
W:  (2, 4)
b:  (1, 4)


In [10]:
forward_output = np.dot(X,W)
print(forward_output.shape)
print(forward_output)

(3, 4)
[[ 1 23 10 16]
 [ 3 53 26 40]
 [ 5 83 42 64]]


In [11]:
forward_output += b

In [12]:
print(forward_output)

[[ 2 25 13 21]
 [ 4 55 29 45]
 [ 6 85 45 69]]
